### ISSUE TITLE
Can't compile with g++ 4.8.2 on ubuntu

### ISSUE THREAD

**Issue by roman4e** [rofl0r/conpix#2]
Getting next error

``` bash
$./build.sh                                                                     
```

```
In file included from ../NsNcurses.h:12:0,
                 from ../ConsoleWindow.h:15,
                 from ../ConsoleWindow.cpp:9:
../ConsoleWindow.cpp: In member function ‘bool ConsoleWindow::useColorPair(int)’:
../ConsoleWindow.cpp:159:13: error: expected type-specifier before ‘chtype’
  lastattr = COLOR_PAIR(pair+1);
             ^
../ConsoleWindow.cpp:159:13: error: expected ‘>’ before ‘chtype’
../ConsoleWindow.cpp:159:13: error: expected ‘(’ before ‘chtype’
../ConsoleWindow.cpp:159:13: error: ‘chtype’ was not declared in this scope
../ConsoleWindow.cpp:159:13: note: suggested alternative:
In file included from ../NsNcurses.h:12:0,
                 from ../ConsoleWindow.h:15,
                 from ../ConsoleWindow.cpp:9:
/usr/include/curses.h:150:23: note:   ‘ncurses::chtype’
 typedef unsigned long chtype;
                       ^
../ConsoleWindow.cpp:159:31: error: expected ‘)’ before ‘;’ token
  lastattr = COLOR_PAIR(pair+1);
                               ^
g++: error: ./ConsoleWindow.o: No such file or directory
mv: cannot stat ‘a.out’: No such file or directory
Finished building target: conpix
you can now run testt/conpix executable
```
